name: QiwiSnake
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt update
          # Устанавливаем всё, включая Java (openjdk) и нужные библиотеки
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython Kivy

      - name: Build with Buildozer
        run: |
          # Если файла настроек нет, создаем его
          if [ ! -f buildozer.spec ]; then buildozer init; fi
          
          # ПРИНЯТИЕ ЛИЦЕНЗИЙ (решает ошибку Aidl not found)
          yes | buildozer android debug || true
          
          # Финальная сборка с подробным логом
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: QiwiSnake-App
          path: bin/*.apk
