name: QiwiSnake
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Используем свежую версию

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt update
          # Добавляем openjdk-17-jdk и исправляем пакет libtinfo
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython Kivy

      - name: Build with Buildozer
        run: |
          # 1. Создаем конфиг, если его вдруг нет
          if [ ! -f buildozer.spec ]; then buildozer init; fi
          
          # 2. ПРИНИМАЕМ ЛИЦЕНЗИИ (это уберет ошибку Aidl not found)
          yes | buildozer android debug || true
          
          # 3. Запускаем основную сборку
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: QiwiSnake-App
          path: bin/*.apk
