name: QiwiSnake
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04  # Фиксируем старую добрую Ubuntu, где 3.8 роднее
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          sudo apt update
          # Ставим Java 17 (нужна для новых Android SDK) и системные либы
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 Kivy  # Фиксируем версию Cython для 3.8

      - name: Accept Android Licenses
        run: |
          # Это самое важное, чтобы не было "Aidl not found"
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          yes | buildozer android debug || true

      - name: Final Build
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: QiwiSnake-APK
          path: bin/*.apk
